EE_LIB_NAME = librac2ntscj.a
EE_DEFS = -DGC_NTSCJ -DRAC2_NTSCJ -DRAC_NTSCJ -DNTSCJ -DGC_V100 -DRAC2_V100 -DRAC_V100 -DGC_NTSCJ_V100 -DRAC2_NTSCJ_V100 -DRAC_NTSCJ_V100

include ${CURDIR}/Makefile.defs
include $(PS2SDK)/samples/Makefile.pref
include ${CURDIR}/Makefile.eeglobal
