EE_LIB_NAME = librac2ntscu.a
EE_DEFS = -DGC_NTSCU -DRAC2_NTSCU -DRAC_NTSCU -DNTSCU -DGC_V100 -DRAC2_V100 -DRAC_V100 -DGC_NTSCU_V100 -DRAC2_NTSCU_V100 -DRAC_NTSCU_V100

include ${CURDIR}/Makefile.defs
include $(PS2SDK)/samples/Makefile.pref
include ${CURDIR}/Makefile.eeglobal
