#ifndef _LIBRAC2_PLAYER_H_
#define _LIBRAC2_PLAYER_H_

#include <tamtypes.h>
#include "types.h"
#include "math3d.h"
#include "pad.h"
#include "math.h"
#include "moby.h"

#define PLAYER_1_STRUCT		((Player*)0x00189e20)
#define PLAYER_STRUCT		PLAYER_1_STRUCT

typedef enum PlayerState {
	PLAYER_STATE_IDLE = 0,
	PLAYER_STATE_LOOK = 1,
	PLAYER_STATE_WALK = 2,
	PLAYER_STATE_SKID = 3,
	PLAYER_STATE_CROUCH = 4,
	PLAYER_STATE_QUICK_TURN = 5,
	PLAYER_STATE_FALL = 6,
	PLAYER_STATE_JUMP = 7,
	PLAYER_STATE_GLIDE = 8,
	PLAYER_STATE_RUN_JUMP = 9,
	PLAYER_STATE_LONG_JUMP = 10,
	PLAYER_STATE_FLIP_JUMP = 11,
	PLAYER_STATE_JINK_JUMP = 12,
	PLAYER_STATE_ROCKET_JUMP = 13,
	PLAYER_STATE_DOUBLE_JUMP = 14,
	PLAYER_STATE_HELI_JUMP = 15,
	PLAYER_STATE_CHARGE_JUMP = 16,
	PLAYER_STATE_WALL_JUMP = 17,
	PLAYER_STATE_WATER_JUMP = 18,
	PLAYER_STATE_COMBO_ATTACK = 19,
	PLAYER_STATE_JUMP_ATTACK = 20,
	PLAYER_STATE_THROW_ATTACK = 21,
	PLAYER_STATE_GET_HIT = 22,
	PLAYER_STATE_LEDGE_GRAB = 23,
	PLAYER_STATE_LEDGE_IDLE = 24,
	PLAYER_STATE_LEDGE_TRAVERSE_LEFT = 25,
	PLAYER_STATE_LEDGE_TRAVERSE_RIGHT = 26,
	PLAYER_STATE_LEDGE_JUMP = 27,
	PLAYER_STATE_VISIBOMB = 28,
	PLAYER_STATE_TARGETING = 29,
	PLAYER_STATE_GUN_WAITING = 30,
	PLAYER_STATE_WALLOPER_ATTACK = 31,
	PLAYER_STATE_ATTACK_BOUNCE = 32,
	PLAYER_STATE_ROCKET_STOMP = 33,
	PLAYER_STATE_GLOVE_ATTACK = 34,
	PLAYER_STATE_GRAPPLE_SHOOT = 35,
	PLAYER_STATE_GRAPPLE_PULL = 36,
	PLAYER_STATE_GRAPPLE_PULL_VEHICLE = 37,
	PLAYER_STATE_SUCK_CANNON = 38,
	PLAYER_STATE_GRIND = 39,
	PLAYER_STATE_GRIND_JUMP = 40,
	PLAYER_STATE_GRIND_SWITCH_JUMP = 41,
	PLAYER_STATE_GRIND_ATTACK = 42,
	PLAYER_STATE_SWING = 43,
	PLAYER_STATE_SWING_FALL = 44,
	PLAYER_STATE_RECOIL = 45,
	PLAYER_STATE_ICE_WALK = 46,
	PLAYER_STATE_DEVASTATOR = 47,
	PLAYER_STATE_SLIDE = 48,
	PLAYER_STATE_VEHICLE = 49,
	PLAYER_STATE_SWIMUNDER = 50,
	PLAYER_STATE_IDLEUNDER = 51,
	PLAYER_STATE_CHARGEUNDER = 52,
	PLAYER_STATE_SWIMSURF = 53,
	PLAYER_STATE_IDLESURF = 54,
	PLAYER_STATE_BOLT_CRANK = 55,
	PLAYER_STATE_LAVA_JUMP = 56,
	PLAYER_STATE_DEATH = 57,
	PLAYER_STATE_BOARD = 58,
	PLAYER_STATE_MAGNE_WALK = 59,
	PLAYER_STATE_GRIND_HIT = 62,
	PLAYER_STATE_GRIND_JUMP_TURN = 63,
	PLAYER_STATE_VENDOR_BOOTH = 98,
	PLAYER_STATE_NPC = 99,
	PLAYER_STATE_WALK_TO_POS = 100,
	PLAYER_STATE_SKID_TO_POS = 101,
	PLAYER_STATE_IDLE_TO_POS = 102,
	PLAYER_STATE_JUMP_TO_POS = 103,
	PLAYER_STATE_QUICKSAND_SINK = 104,
	PLAYER_STATE_QUICKSAND_JUMP = 105,
	PLAYER_STATE_DROWN = 106,
	PLAYER_STATE_MAGNE_ATTACK = 111,
	PLAYER_STATE_MAGNE_JUMP = 112,
	PLAYER_STATE_CUT_SCENE = 113,
	PLAYER_STATE_WADE = 114,
	PLAYER_STATE_ZIP = 115,
	PLAYER_STATE_GET_HIT_SURF = 116,
	PLAYER_STATE_GET_HIT_UNDER = 117,
	PLAYER_STATE_DEATH_FALL = 118,
	PLAYER_STATE_SLOPESLIDE = 120,
	PLAYER_STATE_JUMP_BOUNCE = 121,
	PLAYER_STATE_DEATHSAND_SINK = 122,
	PLAYER_STATE_LAVA_DEATH = 123,
	PLAYER_STATE_CHARGE = 125,
	PLAYER_STATE_ICEWATER_FREEZE = 126,
	PLAYER_STATE_ELECTRIC_DEATH = 127,
	PLAYER_STATE_ROCKET_HOVER = 128,
	PLAYER_STATE_ELECTRIC_DEATH_UNDER = 129,
	PLAYER_STATE_SKATE = 130,
	PLAYER_STATE_MOON_JUMP = 131,
	PLAYER_STATE_JET = 132,
	PLAYER_STATE_THROW_SHURIKEN = 133,
	PLAYER_STATE_RACEBIKE = 134,
	PLAYER_STATE_SPEEDBOAT = 135,
	PLAYER_STATE_HOVERPLANE = 136,
	PLAYER_STATE_LATCH_GRAB = 137,
	PLAYER_STATE_LATCH_IDLE = 138,
	PLAYER_STATE_LATCH_JUMP = 139,
	PLAYER_STATE_PULLSHOT_ATTACH = 140,
	PLAYER_STATE_PULLSHOT_PULL = 141,
	PLAYER_STATE_GET_FLATTENED = 142,
	PLAYER_STATE_SKYDIVE = 143,
	PLAYER_STATE_WAIT_FOR_RESURRECT = 144,
	PLAYER_STATE_FLAIL_ATTACK = 145,
	PLAYER_STATE_MAGIC_TELEPORT = 146,
	PLAYER_STATE_TELEPORT_IN = 147,
	PLAYER_STATE_DEATH_NO_FALL = 148,
	PLAYER_STATE_TURRET_DRIVER = 152,
	PLAYER_STATE_WAIT_FOR_JOIN = 154,
	PLAYER_STATE_DROPPED = 155,
	PLAYER_STATE_CNT = 156
} PlayerState;

typedef enum PlayerType {
	PLAYER_TYPE_IDLE = 0,
	PLAYER_TYPE_WALK = 1,
	PLAYER_TYPE_FALL = 2,
	PLAYER_TYPE_LEDGE = 3,
	PLAYER_TYPE_JUMP = 4,
	PLAYER_TYPE_GLIDE = 5,
	PLAYER_TYPE_ATTACK = 6,
	PLAYER_TYPE_GET_HIT = 7,
	PLAYER_TYPE_SHOOT = 8,
	PLAYER_TYPE_BUSY = 9,
	PLAYER_TYPE_BOUNCE = 10,
	PLAYER_TYPE_STOMP = 11,
	PLAYER_TYPE_CROUCH = 12,
	PLAYER_TYPE_GRAPPLE = 13,
	PLAYER_TYPE_SWING = 14,
	PLAYER_TYPE_GRIND = 15,
	PLAYER_TYPE_SLIDE = 16,
	PLAYER_TYPE_SWIM = 17,
	PLAYER_TYPE_SURF = 18,
	PLAYER_TYPE_HYDRO = 19,
	PLAYER_TYPE_DEATH = 20,
	PLAYER_TYPE_BOARD = 21,
	PLAYER_TYPE_RACEBOARD = 22,
	PLAYER_TYPE_SPIN = 23,
	PLAYER_TYPE_NPC = 24,
	PLAYER_TYPE_QUICKSAND = 25,
	PLAYER_TYPE_ZIP = 26,
	PLAYER_TYPE_HOLO = 27,
	PLAYER_TYPE_CHARGE = 28,
	PLAYER_TYPE_ROCKET_HOVER = 29,
	PLAYER_TYPE_JET = 30,
	PLAYER_TYPE_RACEBIKE = 31,
	PLAYER_TYPE_SPEEDBOAT = 32,
	PLAYER_TYPE_PULL = 33,
	PLAYER_TYPE_LATCH = 34,
	PLAYER_TYPE_LADDER = 36,
	PLAYER_TYPE_SKYDIVE = 37,
	PLAYER_TYPE_CNT = 38
} PlayerType;

typedef struct HeroMove {
/* 0x00 */ VECTOR behavior;
/* 0x10 */ VECTOR external;
/* 0x20 */ VECTOR actual;
/* 0x30 */ VECTOR actualFromBehavior;
/* 0x40 */ VECTOR actualFromBehaviorGrav;
/* 0x50 */ VECTOR actualFromBehavior2D;
/* 0x60 */ VECTOR actualFromExternal;
/* 0x70 */ VECTOR taper;
/* 0x80 */ float speed;
/* 0x84 */ float speed2D;
/* 0x88 */ float forwardSpeed;
/* 0x8c */ float ascent;
/* 0x90 */ float zSpeed;
/* 0x94 */ float externalSpeed;
/* 0x98 */ int pad[2];
} HeroMove;

typedef struct HeroTurn {
/* 0x00 */ float ideal;
/* 0x04 */ float speed;
/* 0x08 */ float accel;
/* 0x0c */ float diff;
} HeroTurn;

typedef struct HeroMotionControl {
/* 0x00 */ float targetSpeed;
/* 0x04 */ float currentSpeed;
/* 0x08 */ int stateFrame;
/* 0x0c */ int unk_0c;
/* 0x10 */ int transTimerA;
/* 0x14 */ int transTimerB;
/* 0x18 */ int unk_18;
/* 0x1c */ int unk_1c;
/* 0x20 */ int unk_20;
/* 0x24 */ int unk_24;
/* 0x28 */ int unk_28;
/* 0x2c */ int unk_2c;
/* 0x30 */ int unk_30;
/* 0x34 */ int unk_34;
} HeroMotionControl;

/* start:
Aranos: 0x00189e20
Museum: 0x00189e20
*/
typedef struct Hero { // 0x2540
/* 0x0000 */ MATRIX mtx;
/* 0x0040 */ MATRIX invMtx;
/* 0x0080 */ VECTOR pos;
/* 0x0090 */ VECTOR rot;
/* 0x00a0 */ char unk_00a0[0x40];
/* 0x00e0 */ HeroMove move;
/* 0x0180 */ HeroTurn turn;
/* 0x0190 */ HeroMotionControl motion;
/* 0x01c8 */ char unk_01c8[0xa50];
/* 0x0c18 */ Moby *unk_Moby_0c18;
/* 0x0c1c */ char unk_0c1c[0x1394];
/* 0x1fb0 */ VECTOR sitckInput;
/* 0x1fc0 */ char unk_1fc0[0x2d0];
/* 0x2290 */ Moby *pMoby;
/* 0x2294 */ int state;
/* 0x2298 */ int stateTimer;
/* 0x229c */ int stateType;
/* 0x22a0 */ int previousState;
/* 0x22a4 */ int previousType;
/* 0x22a8 */ int previousStateTimer;
/* 0x22ac */ int previousPreviousState;
/* 0x22b0 */ int previousPreviousType;
/* 0x22b4 */ char subState;
/* 0x22b5 */ char unk_22b5;
/* 0x22b6 */ char unk_22b6;
/* 0x22b7 */ char unk_22b7;
/* 0x22b8 */ char stateControlLock;
/* 0x22b9 */ char unk_22b9;
/* 0x22ba */ char unk_22ba;
/* 0x22bb */ char unk_22bb;
/* 0x22bc */ char movementControlLock;
/* 0x22bd */ char cutsceneControlLock;
/* 0x22be */ char unk_22be;
/* 0x22bf */ char unk_22bf;
/* 0x22c0 */ char unk_22c0;
/* 0x22c1 */ bool resetLevel;
/* 0x22c2 */ char unk_22c2[0x1f6];
/* 0x24b8 */ float inputMagnitude;
/* 0x24bc */ char unk_24bc[0x10];
/* 0x24cc */ int hitpoints;
/* 0x24d0 */ char unk_24d0[0x28];
/* 0x24f8 */ u16 timer_24f8;
/* 0x24fa */ u16 timer_24fa;
/* 0x24fc */ char unk_24fc[0x3c];
/* 0x2538 */ int forceGadgetSwitch;
/* 0x253c */ int unk_253c;
} Hero;
typedef Hero Player;

int playerCanControl(void);

#endif
